### ISSUE TITLE
Sort Task names in output task selection menu

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling-portal#177]
<a href="https://jira.activeeon.com/browse/PORTAL-374" title="PORTAL-374">Original issue</a> created by <a href="mailto:fabien.viale_AT_activeeon.com">Fabien Viale</a> on 28, Feb 2014 at 10:55 AM - PORTAL-374

<hr />

When there are a lot of tasks it is unpractical to go through the whole list in order to find the task whose logs is to be printed.

A dictionary sort would help

**Comment by fviale** [comment]
Raised the priority of this issue as it has been reported by many clients. In case there is a big number of tasks, the fact that the drop/down list is not sorted is a real issue.

**Comment by lpellegr** [comment]
https://github.com/ow2-proactive/scheduling-portal/pull/268

**Comment by lpellegr** [comment]
No longer valid since the output task dropdown has been redesign to offer only two options _Selected job_ or _Selected task_.
