### ISSUE TITLE
Show node monitoring history in RM portal

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling-portal#184]
<a href="https://jira.activeeon.com/browse/PORTAL-388" title="PORTAL-388">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 18, Apr 2014 at 15:17 PM - PORTAL-388

<hr />

similar to what we do for the server stat.

**Comment by Mykhailenko** [comment]
Implemented long time ago!
