### ISSUE TITLE
Jobs pagination is not bounded as it should

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#243]
Let's say there is _200_ jobs in finished state in the scheduler, then since the default page size for the scheduler web portal is _50_ it should be allowed to click on _Next_ button only _3_ times. However, it is possible to click _4_ times. Consequently, page _4_ is empty.

Below is a screenshot that shows the issue:

![capture d ecran de 2015-10-20 08-49-28](https://cloud.githubusercontent.com/assets/128898/10600004/a6c83a50-7707-11e5-8c2b-679a8d5f220f.png)

**Comment by sandrineBeauche** [comment]
fixed in the commit 2635fd066f396aafa62f1ec6ae7af0598265850b
