### ISSUE TITLE
Tasks detail view is broken

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#252]
When a job is selected, then on Tasks view tab it was possible to click on a task (grey arrow) to get additional information. It is currently broken with current master on Chrome.

Using master:
![capture d ecran de 2015-11-03 15-04-46](https://cloud.githubusercontent.com/assets/128898/10909911/79aaee06-823c-11e5-879e-dacaa975d3b2.png)

Using 6.3.0:
![capture d ecran de 2015-11-03 15-00-20](https://cloud.githubusercontent.com/assets/128898/10909916/8247c566-823c-11e5-8f40-c13349f8da79.png)

**Comment by lpellegr** [comment]
I think the regression has been introduced by the upgrade of SmartGWT with PR #244.

**Comment by sandrineBeauche** [comment]
I take a look

**Comment by sandrineBeauche** [comment]
solved in the taskCentric pull request
