### ISSUE TITLE
Spacing issue with jobs filtering checkboxes

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#253]
Below are screenshots to highlight the issue by comparing current master with 6.3.0.

Current master:

![spacing-issue-master](https://cloud.githubusercontent.com/assets/128898/11057291/0cad561a-878a-11e5-8417-ac7a9d79e694.png)

Version 6.3.0:

![spacing-issue-6 3 0](https://cloud.githubusercontent.com/assets/128898/11057295/1153c622-878a-11e5-963a-a1ea487b381c.png)

@sandrineBeauche I think it is again related to changes introduced by Smart GWT version we are now using.

**Comment by sandrineBeauche** [comment]
fixed in commit fd76ca76c5186c95045045315a3e0d52a3dd4a55
