### ISSUE TITLE
modify dropdown lists in output, server logs and preview views

### ISSUE THREAD

**Issue by sandrineBeauche** [ow2-proactive/scheduling-portal#255]
We should replace this dropdown list by another lit where we choose between the selected job and the selected task(s?). Tasks where we want to retrieve output can be selected from the task view or from the task-centric view.

**Comment by lpellegr** [comment]
https://github.com/ow2-proactive/scheduling-portal/pull/268

**Comment by fviale** [comment]
pull request #268 merged
