### ISSUE TITLE
Spacing issue at top of Executions list

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#259]
![capture d ecran de 2015-11-26 12-51-33-red](https://cloud.githubusercontent.com/assets/128898/11422539/f36d2f4e-943c-11e5-8d4e-51b50e1e6857.png)

**Comment by sandrineBeauche** [comment]
fixed in version 7.0.1

**Comment by lpellegr** [comment]
@sandrineBeauche I am not sure it is 7.0.1.
