### ISSUE TITLE
Job pagination displays more jobs per page than expected 

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#260]
Lets say you have 25 jobs submitted and jobs page size set to 5. Then, from a page to another there is sometimes more than 5 jobs displayed per page. However, the number of pages is correct.

![capture_d_39_cran_vid_o_de_26-11-2015_13_02_32_w](https://cloud.githubusercontent.com/assets/128898/11422777/f3655146-943e-11e5-8f44-6b60caf49f07.gif)

Issue occurs with current master eb5a57d7a7862959d9ad9e9cee1285224468edb0.

**Comment by lpellegr** [comment]
I have identified the root cause of the issue. Pagination is made possible by fetching data in chunks. To this aim, two main parameters (_offset_ and _range_) are forwarded from the Scheduler Web portail to Scheduler internals. At the scheduler core, these parameters are eventually used to fetch data from the database. 

The problem is that parameter _range_ is used with a semantic which is different at Web portail and database level. For the latter, _range_ is interpreted as the number of items to return whereas in the former it is used as the index of the last item.

**Comment by lpellegr** [comment]
Even at the database level, _range_ has different meaning if it is used for fetching tasks or jobs.

There are at least 3 solutions:

  1. Update Web portal to have same semantic as Scheduler core (_range_ is the maximum number of results to return, i.e. page size);
  2. Update Scheduler core to match Web portal semantic (_range_ is the last item to retrieve);
  3. Update Web portal only for jobs pagination.

Solution 1 or 2 will make code easier to understand and clear for the future since it will force a consistent semantic for _range_ property. 

Solution 3 is the faster for fixing the issue but keep meaning complex.

Personally, I am for solution 1 due to the following reasons:

  - Definition of _range_ word: "the area of variation between upper and lower limits on a particular scale."
  - [Google drive REST API](https://developers.google.com/drive/v2/reference/changes/list) uses `maxResults` parameter for pagination which is similar to semantic proposed with solution 1.
  - [Github REST API](https://developer.github.com/v3/#pagination) uses `per_page` parameter which has also same semantic as the one used with solution 1.

**Comment by paraita** [comment]
I just arrived to the same conclusion that job and task pagination should have the same semantic meaning. Either solution is fine with me (it will impact the scheduler portal as well as the scheduling project). [This page](http://blog.octo.com/designer-une-api-rest/#pagination) has some information on general REST practices, and has a comparison of different pagination solutions at the GAFA.

**Comment by paraita** [comment]
I double-checked the SchedulerDBManager (which handles the jobs and tasks retrieval) and it is using the following methods for pagination:
* setFirstResult(int index)
* setMaxResults(int size)
So it is actually expecting an *amount* of items to retrieve, and **not** the index of the last item (I was wrong :-S)
If we decide to go for the solution 1, I think it won't be necessary to modify the SchedulerDBManager.

**Comment by lpellegr** [comment]
@paraita A small change is required in `SchedulerStateRest` because of `SchedulerStateRest#getBoundaries(int offset, int limit)`. Currently, if input is _10_ and _5_ respectively, then `limit` value will be changed to _110_.

**Comment by lpellegr** [comment]
There is also a difference of semantic compared to solution 1 in `JobState#getTasksPaginated` and `JobState#getTaskByTagPaginated`. I will fix it.
