### ISSUE TITLE
Update copyright year in about dialog

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#278]
Currently, copyright year is 2015. It should be 2016. The source code can probably be updated to use the current year, thus preventing updates in the future.

![screen shot 2016-02-27 at 14 26 54](https://cloud.githubusercontent.com/assets/128898/13373158/fa8bd692-dd5f-11e5-867e-08f2121237cd.png)

**Comment by fviale** [comment]
Automate Year increase
