### ISSUE TITLE
Update Visualization tab to display execution attempts and task ID

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#292]
Denis has requested to update the way Tasks are displayed in the _Visualization_ tab of the Scheduler Web portal. The idea is to display two additional information: the number of execution attempts and the task ID. In case the Task is auto-generated (i.e. for a loop) the ID of the auto-generated task must be displayed.

The feature was initially requested in order to be able to easily identify a Task that needs to be restarted from an In-Error state.

**Comment by marcocast** [comment]
linked with #293

**Comment by fviale** [comment]
cannot link the visualization to task id as replicated tasks are displayed as a single box in the visualization view
