### ISSUE TITLE
Display Job input variables for selected Job

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#314]
It is possible to submit multiple instances of a same Workflow. These instances are displayed as Jobs in the Scheduler portal. Unfortunately, the Scheduler portal is not displaying the variables and their value which have been set for a Workflow instance. 

Having such information in the Scheduler portal would be really convenient to track, differentiate, develop and debug a Workflow with different input values. Thus, avoiding to touch the code of the tasks for such basic use case.

**Comment by fviale** [comment]
You can see them in the server logs.

**Comment by lpellegr** [comment]
Ok, not user friendly at all but since it is present I close the issue.

**Comment by fviale** [comment]
You can maybe open another issue for a more user-friendly version of this
info
