### ISSUE TITLE
Node removal is not working as described

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#341]
The Resource Manager portal offers an option to remove one or more Nodes at once. Upon removal, a popup appears and an option is proposed:

![Node Removal Option](https://cloud.githubusercontent.com/assets/128898/22983066/459ff764-f3a1-11e6-851f-89eb5cb64d45.png)

By default, the option _Wait task completion on busy Nodes_ is disabled. In that case, the Node should be removed immediately. However, removing a busy Node with the option disabled put the Node in _TO_BE_REMOVED_ state. As a consequence, the RM waits for the Task running on the Node to complete. In contrast, enabling the option removes the Node immediately.

Steps to reproduce:

1. Open the Studio.
2. Create a new Workflow with a single Bash Task.
3. Put `sleep 30` as the Task script.
4. Execute the Workflow.
5. Open the Resource Manager portal.
6. Right click on the Node that is busy and select _Remove_.
7. On the popup that appears, click on _OK_.

The node should disappear immediately, without waiting for the completion of the Task running on it. Unfortunately, it is not the case. 

The problem is not new. I am able to reproduce with release _7.5.0_.

Either the label associated with the option has to be considered wrong or the label description for the option is correct and then, the value that is forwarded to the Scheduler REST API for the _preempt_ option is the opposite of what it should.

**Comment by jrochas** [comment]
The option was meant to be used in the opposite way than it was defined.
Addressed in #429
