### ISSUE TITLE
RM Portal should disable Compact and Hierarchical Views (or simplify) when over 1000 nodes

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/scheduling-portal#376]
When RM Portal shows more than 1,000 nodes, it becomes very slow and memory consuming.
Checking "my nodes" manually hides the nodes from compact view, and it helps a lot to scale.
If we forgot to do it, it puts the REST Server under pressure as well.
Making this automatic avoid system instabilities. Anyway, above 1000 nodes, this interface is useless. GWT framework was not designed to work with so many objects.
Then, RM portal get slower after 40,000 Nodes.

**Comment by fviale** [comment]
RM Portal performance has been vastly improved, with pagination on node events, etc. Closing issue.
