### ISSUE TITLE
When submitting a malformed XML document, the job submission through the SubmitWindow hangs indefinitely  

### ISSUE THREAD

**Issue by zeineb** [ow2-proactive/scheduling-portal#378]
Same issue for non XML files.

**Comment by zeineb** [comment]
<img width="1275" alt="capture d ecran 2017-11-14 a 11 01 04" src="https://user-images.githubusercontent.com/368264/32774453-9ca81382-c92c-11e7-872f-faa41b7ffc4e.png">

**Comment by amouhoub** [comment]
Solved in PR [#389](https://github.com/ow2-proactive/scheduling-portal/pull/389)
