### ISSUE TITLE
submitted jobs with Execution Calendars are only executed but not planned according to EC

### ISSUE THREAD

**Issue by amouhoub** [ow2-proactive/scheduling-portal#395]
When submitting a new job either from a file or from the catalog, if it contains EC information, a new option (Planned according to embedded EC information) shows up as in the attached picture below.

However, when pressing submit, the job gets executed immediately and does not get submitted to the job-planner. In other words, it is not planned but only executed once immediately.

![capture d ecran 2017-12-13 a 09 56 58](https://user-images.githubusercontent.com/1918419/33930078-0136b26a-dfec-11e7-9249-409c32a821fe.png)

**Comment by zeineb** [comment]
I'm on it.

**Comment by amouhoub** [comment]
Fixed in PR [#400](https://github.com/ow2-proactive/scheduling-portal/pull/400)
