### ISSUE TITLE
Cannot submit catalog workflows from the scheduler on firefox

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/scheduling-portal#398]
On firefox, on the scheduler portal, when submitting a workflow from the catalog, the button "import workflow" doesn't appear and prevents to submit the workflow.

Firefox picture, "import workflow" doesn't appear :
![firefox_scheduler](https://user-images.githubusercontent.com/16114403/34200483-8f2d8c30-e571-11e7-99dd-41f8801aa851.png)

Chromium picture, "import workflow" appears :
![chromium_scheduler](https://user-images.githubusercontent.com/16114403/34200486-91766502-e571-11e7-9186-34cd240401e7.png)

**Comment by amouhoub** [comment]
Fixed in #601
