### ISSUE TITLE
Uploaded files are lost when node source policy is changed

### ISSUE THREAD

**Issue by jrochas** [ow2-proactive/scheduling-portal#437]
How to reproduce: 
- add or edit a node source
- upload a file in a file-based field (e.g. in the infrastructure of the node source)
- change infrastructure or policy
- look again at the field where you had uploaded the file
- the former uploaded file is gone

**Comment by Mykhailenko** [comment]
Mitigated in version 10.0.0.
We added additional alert in https://github.com/ow2-proactive/scheduling-portal/commit/693d7bc28e9f62f1a75418f26222789010c4365a.
