### ISSUE TITLE
Nodes history stuck with error after updating time window

### ISSUE THREAD

**Issue by vinseon** [ow2-proactive/scheduling-portal#530]
With the new `Nodes needed` line in the nodes history graph, the graph can be stuck refreshing forever after changing
![capture d ecran de 2019-03-08 19-02-12](https://user-images.githubusercontent.com/24268144/54046518-df7e9d80-41d4-11e9-8f60-76cdc5a0a922.png)
 the time window from the select box (the error happened when trying to change from 10 min. to 1 hour).
The following errors keep appearing in the RM portal:
`Index: 151, Size: 151`

**Comment by Mykhailenko** [comment]
Fixed in 10.0.0
