### ISSUE TITLE
Wrong input control behavior in portal settings

### ISSUE THREAD

**Issue by mboussaa** [ow2-proactive/scheduling-portal#543]
Editing and submitting new setting values in portal -> settings allows introducing wrong values (e.g., less than 5 jobs page size). Then, you can check the warning message after, when you go back to the settings. This is a wrong behavior!

The portal settings should not allow the user to submit the new settings unless the inputs are valid!

**Comment by chloegugli** [comment]
Here is the PR fix : https://github.com/ow2-proactive/scheduling-portal/pull/555
@mboussaa I also noticed that cancel doesn't put the form as it was before opening the settings modal, should we open another issue?

**Comment by chloegugli** [comment]
Here is the issue : https://github.com/ow2-proactive/scheduling-portal/issues/557
