### ISSUE TITLE
Match all should not return any job when specifying two different values for the same job filter

### ISSUE THREAD

**Issue by mboussaa** [ow2-proactive/scheduling-portal#551]
"Match all" should not return any job when specifying two different values for the same filter.
e.g., id equals to 1 and id equals to 3 with "match all" should not return any job as the intersection is empty.
<img width="436" alt="Screenshot 2019-04-09 at 14 17 07" src="https://user-images.githubusercontent.com/5878565/55799967-df730580-5ad2-11e9-8dc7-b49f82eed475.png">

**Comment by mbenguig** [comment]
More generally, other combinations of filters produce incoherent results (filtering job names using 2 distinct contains,  should return job containing both strings in their name)

name.contains("EF") && name.contains("AE") does not return jobs named "AEF" (return nothing)

**Comment by fviale** [comment]
If we want to support advanced filtering operations, we need to switch from plain graphql to use graphcool, which supports various kind of filtering:
https://www.graph.cool/docs/reference/graphql-api/query-api-nia9nushae#type-aggregation-queries

**Comment by mbenguig** [comment]
Fixed with https://github.com/ow2-proactive/scheduling-portal/pull/553
