### ISSUE TITLE
Incorrect behavior of the multiline credential feature in third-party credentials

### ISSUE THREAD

**Issue by mboussaa** [ow2-proactive/scheduling-portal#591]
**Platform:** try
**Bug:** The password in the credential textfield become visible to everyone when multiline is activated 
**Severity:** minor
**Steps to reproduce:**
-go to the scheduling portal 
-Portal -> manage third-party credentials
-check multiline credentials checkbox
-The password in the credential textfield become visible to everyone
**How to fix:**
keep the credential value hidden for multiline and unique line, and a checkbox that enables to show the password according to the user choice.

**Comment by Mykhailenko** [comment]
I did not find any suitable smartgwt widget to fulfill our needs.
There are single line password field where characters are hidden, and multi line text are where characters are visible.
