### ISSUE TITLE
Tasks-centric view: Searching for tasks by Tag hangs

### ISSUE THREAD

**Issue by mboussaa** [ow2-proactive/scheduling-portal#631]
In Tasks-centric view, searching for tasks by Gag is faulty. Whatever value given (incorrect, correct), it hangs the server. The exception should be caught. 
![image](https://user-images.githubusercontent.com/5878565/65606239-c986cd80-dfaa-11e9-8307-c15bbfca9c6d.png)

**Comment by MaelAudren** [comment]
@Mykhailenko can you have a look to this bug while you are working on tasks centric view ?

**Comment by MaelAudren** [comment]
Fixed by https://github.com/ow2-proactive/scheduling/pull/3660
