### ISSUE TITLE
Rm portal: Failed to fetch Statistics History when internet is off in local dynamic policy

### ISSUE THREAD

**Issue by mboussaa** [ow2-proactive/scheduling-portal#635]
Getting the following error when having dynamic policy locally + turn off internet when nodes are deployed. I don't know if this is issue can be avoided
11:53:24 UTC+2 Failed to fetch Statistics History: HTTP 404 Not Found

Update: Just figure out that I face the following issue as well in scheduling portal 
11:57:20 UTC+2 Failed to fetch account stats:
HTTP 500 Internal Server Error

**Comment by MaelAudren** [comment]
Due to configuration change at the network level when disconnecting from the internet. This should be handled by the system admin.
