### ISSUE TITLE
"Submitted Job Variables" view does not show variables specified at job submission if submitted from another workflow

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/scheduling-portal#659]
User thinks these variables are the latest set before job submission, but if a job is submitted from another one, this view will display the default ones of the xml... not the ones specified at job submission.

**Comment by MaelAudren** [comment]
@mbenguig can you provide a screenshot please ?

**Comment by mbenguig** [comment]
Not able to reproduce it with the 10.0.3. Maybe it was my mistake.
